name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vtop-api/vtop-api:latest .
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vtop-api/vtop-api:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: vtop-api
        region: asia-south1
        image: asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/vtop-api/vtop-api:latest
